spring:
  application:
    name: myRoad

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.c1qw6siawkhf.us-east-2.rds.amazonaws.com:3306
    username: admin
    password: angotrq0313
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

